Enable Sql Column Change
javers/javers pull request #1064
Opened 2021-03-04 02:58 UTC by gustavodsf

2021-03-13 09:23 UTC, bartoszwalacik commented on javers-persistence-sql/README.md
> +### This repo is a customization of javers
please remove this story about Cesar ...

2021-03-13 09:34 UTC, bartoszwalacik requested changes

2021-03-13 09:34 UTC, bartoszwalacik commented on javers-persistence-sql/src/main/java/org/javers/repository/sql/SqlRepositoryBuilder.java
> +    public SqlRepositoryBuilder withGlobalIdPKColumnName(String globalIdPKColumnName) {
sorry but this amount of boilerplate code is unacceptable.

All this names should be modeled as enum:

```
enum DbNames {
globalIdPKColumnName, globalIdLocalIdColumnName, ...
}
```

an then, the Builder should hold a map with concrete  values for all names `Map<DbNames,String>`

then, we don't need all these methods in the Buidler. Two methods should be enough:

```
public SqlRepositoryBuilder withDbName(DbNames dbName, String value)

public SqlRepositoryBuilder withDbNames(Map<DbNames,String)
```

2021-03-13 10:26 UTC, bartoszwalacik commented
I have serious doubts about this feature. You can already change the names of javers tables.

Why on earth change the col names? Could you please give some example? How would you change the col names in javers table and why?

2021-03-13 10:50 UTC, gustavodsf commented
OK, but the project is for a big oil company, and it has severe database policy, all system has to follow his database column a table name pattern, if don't the system could not enter in production. So if i don't put to follow the pattern i have to create my own, but if this modification is not good for javers, we can give up so you dont waste your time.

2021-03-13 11:04 UTC, bartoszwalacik commented
If this big oil company will pay me via https://github.com/sponsors/bartoszwalacik I will do this feature

2021-03-15 10:44 UTC, gustavodsf commented
I'll talk to them, but let's make it clear if I make these changes, will you still only merge this into the javers repository if they pay as sponsors? Or you never merge this into javers repository ? with this i don't waste your and my time, and if necessary i start to find another solution.  Thanks

2021-03-15 13:36 UTC, bartoszwalacik commented
This new feature (not exactly this code on PR but close) won't be added as a regular feature, beacuse I think it's a corner case. But the feature can be added if sponsored. Sponsored corner cases are fine for me.

2021-03-15 19:56 UTC, closed without merging