Feature: Enable schema management check via config for JaversMongoRepositories
javers/javers pull request #1261
Opened 2023-02-02 18:50 UTC by egasimov

This PR intended to resolve  [Feature: Enable schema management check via config for JaversMongoRepositories #1260](https://github.com/javers/javers/issues/1260)

2023-02-05 20:51 UTC, bartoszwalacik requested changes
please also add this new property to Spring config, see `JaversSqlAutoConfigurationDefaultPropsTest.groovy`

2023-02-06 07:25 UTC, egasimov commented
@bartoszwalacik Thanks for reviewing and sharing comments.
I made following changes and would like you re-review my PR

[Make property schemaManagementEnabled(for MongoRepositories) configurable via Spring](https://github.com/javers/javers/pull/1261/commits/e67a485a6eeceb09b5fda5f0fe239688cad85e59) 

[Make snapshotCollectionName, headCollectionName (for MongoRepositories) configurable via Spring](https://github.com/javers/javers/pull/1261/commits/982e55e348a0849443d734bf3f6cbcdc5ec0fc52)

2023-02-14 14:52 UTC, egasimov commented
Hey @bartoszwalacik , Did you have any chance to look at PR ?

2023-02-14 16:57 UTC, bartoszwalacik commented on javers-spring-boot-starter-mongo/src/test/groovy/org/javers/spring/boot/mongo/JaversMongoStarterDefaultsTest.groovy
> +        javersProperties.schemaManagementEnabled
thanks for adding ale these two missing props

2023-02-14 16:58 UTC, bartoszwalacik approved these changes
LGTM

2023-02-14 17:00 UTC, bartoszwalacik commented
need to push it through CI now

2023-02-14 18:23 UTC, egasimov commented
@bartoszwalacik ,
Could you please consider these changes as 6.9.2, rather than 7.*.* ?

Because my current project which requires above feature was using java 11 and < Spring 3.0.0.

2023-02-17 09:30 UTC, bartoszwalacik commented
@egasimov ok, 6.10.0 is published to the Central

2023-02-18 20:24 UTC, bartoszwalacik commented
merged from here https://github.com/javers/javers/pull/1264

2023-02-18 20:24 UTC, closed without merging